version: '3'

services:
  airflow:
    image: my-airflow:latest
    container_name: airflow
    restart: always

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./credentials:/opt/airflow/credentials

    env_file:
      - .env

    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False

    ports:
      - "8080:8080"

    command: >
      bash -c "
      airflow db init &&
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@test.com || true &&
      airflow webserver --host 0.0.0.0 --port 8080 &
      airflow scheduler
      "